[package]
name = "addcomb"
version = "0.1.0"
authors = ["torrencem <matt@torrencefamily.net>"]
publish = false

[dependencies]
itertools = "0.8.0"
rayon = "1.0.3"
clap = "2.32.0"

[dev-dependencies]
rand = "0.6.5"